#!/usr/bin/env node
'use strict';
/* Writes docs/SOURCES.md from config/sources.json and the registries, so the source registry
 * document can never drift from what the pipeline and the page actually use. */
const fs = require('fs');
const path = require('path');
const { loadEngine } = require('./lib/engine.js');
const ROOT = path.join(__dirname, '..');
const E = loadEngine();
const j = function (p) { return JSON.parse(fs.readFileSync(path.join(ROOT, p), 'utf8')); };
const sources = j('config/sources.json').sources;
const cites = j('data/registry/citations.json');
const tv = j('data/registry/cbic-tariff-values.json');
const duty = j('data/registry/duty-rules.json');
const mcx = j('data/registry/mcx-contracts.json');
const cell = function (s) { return String(s === null || s === undefined ? '' : s).replace(/\|/g, '/').replace(/\n/g, ' '); };
const out = [];
out.push('# Source registry', '', 'Generated by `node pipeline/docs.js` from config/sources.json and data/registry/. Do not edit by hand.', '');
out.push('Each source says how it is obtained, whether this public site may display it and why, how often it changes, when the page marks it STALE, and what happens when it fails.', '');
out.push('## Sources', '');
sources.forEach(function (s) {
  out.push('### ' + s.name + ' (`' + s.id + '`)', '');
  out.push('| Field | Value |', '|---|---|');
  [['Publisher', s.publisher], ['Role', s.role], ['Access', s.access], ['Status', s.status], ['Where', s.url], ['Terms', s.terms + (s.termsCitation ? ' (' + s.termsCitation + ')' : '')],
    ['Public display', (s.publicDisplay.allowed ? 'Allowed. ' : 'BLOCKED. ') + s.publicDisplay.reason], ['Cadence', s.cadence], ['Observation time', s.observationTime],
    ['Goes stale when', E.staleRuleText(s.staleRule)], ['Delay and handling', s.delay], ['Failure modes', (s.failureModes || []).join('; ')], ['Retry', s.retry || '']].forEach(function (r) {
    if (r[1]) out.push('| ' + r[0] + ' | ' + cell(r[1]) + ' |');
  });
  out.push('');
});
out.push('## CBIC tariff values in the registry', '', 'Coverage from ' + tv.coverageFrom + '. Registry last reviewed ' + tv.lastReviewed + '. ' + tv.cadence, '');
out.push('| Notification | Dated | In force | Gold (USD/10 g) | Silver (USD/kg) | Evidence | Document |', '|---|---|---|---|---|---|---|');
tv.entries.forEach(function (e) { out.push('| ' + [e.notification, e.dated, e.effectiveFrom, e.gold, e.silver, e.verification, '[' + cell(e.documentHost) + '](' + e.documentUrl + ')'].map(cell).join(' | ') + ' |'); });
out.push('', '## Duty rules', '', '| Rule | Route | Metals | From | To (exclusive) | BCD | AIDC | Total | Evidence | Citations |', '|---|---|---|---|---|---|---|---|---|---|');
const pct = function (v) { return v === null ? 'not documented' : (v * 100).toFixed(2).replace(/\.00$/, '') + '%'; };
duty.rules.forEach(function (r) { out.push('| ' + [r.ruleId, r.corridorId, r.metals.join(', '), r.effectiveFrom, r.effectiveTo || 'open', pct(r.bcd), pct(r.aidc), pct(r.total), r.verification + (r.inferred ? ' (row inferred)' : ''), r.citations.join(', ')].map(cell).join(' | ') + ' |'); });
out.push('', '## Executability flags', '', duty.execNote || '', '', '| Route | Metal | From | To | Knowable from | Flag | Evidence | Note |', '|---|---|---|---|---|---|---|---|');
duty.exec.forEach(function (x) { out.push('| ' + [x.corridorId, x.metal, x.from, x.to || 'open', x.knowableFrom || x.from, x.code, x.verification, x.note].map(cell).join(' | ') + ' |'); });
out.push('', '## MCX contract specifications', '', '| Product | Lot | Quotation | Quality | Expiry rule | Evidence | Citations |', '|---|---|---|---|---|---|---|');
mcx.specs.forEach(function (s) { out.push('| ' + [s.id, s.lotSize + ' ' + s.lotUnit, s.quotationQuantity + ' ' + s.quotationUnit, s.quality, s.expiryRule, s.verification, s.citations.join(', ')].map(cell).join(' | ') + ' |'); });
out.push('', '| Listed contract | Expiry | Evidence |', '|---|---|---|');
mcx.contracts.forEach(function (c) { out.push('| ' + c.product + ' ' + c.month + ' | ' + c.expiry + ' | ' + c.verification + ' |'); });
out.push('', mcx.listingCycleNote || '', '', 'Tender period: ' + mcx.tenderPeriod.rule + ' (' + mcx.tenderPeriod.citations.join(', ') + '). ' + mcx.holidayCalendar.note, '');
out.push('## Citations', '', 'Verification ladder:', '');
Object.keys(cites.verificationLadder).forEach(function (k) { out.push('- **' + k + '**: ' + cites.verificationLadder[k]); });
out.push('', '| Id | Document | Publisher | Date | Evidence | Host |', '|---|---|---|---|---|---|');
Object.keys(cites.items).forEach(function (k) { const c = cites.items[k]; out.push('| ' + [k, '[' + cell(c.title) + '](' + c.url + ')', c.publisher, c.date || '', c.verification, c.host].map(cell).join(' | ') + ' |'); });
out.push('');
const text = out.join('\n');
if (/[–—]/.test(text)) { console.error('dash found in generated SOURCES.md'); process.exit(1); }
fs.writeFileSync(path.join(ROOT, 'docs', 'SOURCES.md'), text);
console.log('wrote docs/SOURCES.md (' + Math.round(text.length / 1024) + ' KB)');
